import { uid } from "./logic";
import type { NetworkRecord, PipelineTask, ReferralCase, Reminder } from "./types";

const ago = (days: number, hours = 14) => {
  const d = new Date();
  d.setHours(hours, 20, 0, 0);
  d.setDate(d.getDate() - days);
  return d.getTime();
};

function note(days: number, author: string, type: ReferralCase["notes"][0]["type"], text: string) {
  return { id: uid(), at: ago(days), author, type, text };
}

export function seedCases(): Record<string, ReferralCase> {
  const rows: ReferralCase[] = [
    {
      id: "WALSH||10412",
      srno: "10412",
      name: "Walsh, Eleanor",
      branch: "Baltimore",
      state: "MD",
      received: ago(11),
      intake: "Maya Ortiz",
      manager: "Dana Lewis",
      source: "AERS Baltimore City",
      sourceContact: "K. Brennan",
      submittedTo: "Cottage MD",
      status: "Initial Screening",
      reason: "",
      ids: ["CHC10412"],
      lastNoteAt: ago(5),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(11, "Maya Ortiz", "Intake", "New pt from AERS Baltimore. CHC-10412. Level 1 screening requested."),
        note(8, "Maya Ortiz", "Outreach", "Left a VM on the home number. Mailbox not full."),
        note(5, "Maya Ortiz", "Outreach", "No answer. Left a text asking for two screening windows."),
      ],
    },
    {
      id: "CHEN||10388",
      srno: "10388",
      name: "Chen, Marcus",
      branch: "PG County",
      state: "MD",
      received: ago(22),
      intake: "Maya Ortiz",
      manager: "Dana Lewis",
      source: "Prince George's DSS",
      sourceContact: "R. Patel",
      submittedTo: "Cottage MD",
      status: "Initial Screening",
      reason: "",
      ids: ["CHC10388"],
      lastNoteAt: ago(16),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(22, "Maya Ortiz", "Intake", "New patient _RS: PG County. Daughter is POA."),
        note(19, "Maya Ortiz", "Outreach", "No answer, left a VM."),
        note(16, "Maya Ortiz", "Outreach", "Unreachable today. Daughter's cell rings out."),
      ],
    },
    {
      id: "PATEL||10440",
      srno: "10440",
      name: "Patel, Priya",
      branch: "Montgomery",
      state: "MD",
      received: ago(9),
      intake: "Jordan Hale",
      manager: "Dana Lewis",
      source: "Holy Cross Geriatrics",
      sourceContact: "Dr. Singh",
      submittedTo: "Cottage MD",
      status: "Hold — waitlist",
      reason: "Insufficient staff in zip",
      ids: ["CHC10440"],
      lastNoteAt: ago(3),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(9, "Jordan Hale", "Intake", "Hospital d/c Friday. 4 hours AM, 2 hours PM."),
        note(6, "Jordan Hale", "Conversation", "Spoke with daughter — hold for Silver Spring staffing."),
        note(3, "Jordan Hale", "Note", "Recheck county / AERS Monday. Still on waitlist."),
      ],
    },
    {
      id: "ALVAREZ||10461",
      srno: "10461",
      name: "Alvarez, Rosa",
      branch: "Anne Arundel",
      state: "MD",
      received: ago(2),
      intake: "Jordan Hale",
      manager: "Dana Lewis",
      source: "Anne Arundel Medical",
      sourceContact: "CM Desk",
      submittedTo: "Cottage MD",
      status: "Initial Screening",
      reason: "",
      ids: ["CHC10461"],
      lastNoteAt: ago(1),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(2, "Jordan Hale", "Intake", "New pt. Screening is set pending callback."),
        note(1, "Jordan Hale", "Scheduling", "Member asked to schedule Level 1 for Thursday afternoon."),
      ],
    },
    {
      id: "BROOKS||10391",
      srno: "10391",
      name: "Brooks, DeShawn",
      branch: "Baltimore",
      state: "MD",
      received: ago(14),
      intake: "Maya Ortiz",
      manager: "Dana Lewis",
      source: "Johns Hopkins Bayview",
      sourceContact: "SW Lane",
      submittedTo: "Cottage MD",
      status: "Pending documents",
      reason: "",
      ids: ["CHC10391"],
      lastNoteAt: ago(9),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(14, "Maya Ortiz", "Intake", "Medicaid pending. Document list sent."),
        note(9, "Maya Ortiz", "Documents", "Waiting on SSN card and bank statement. Passport on file."),
      ],
    },
    {
      id: "WHITAKER||10220",
      srno: "10220",
      name: "Whitaker, James",
      branch: "Howard County",
      state: "MD",
      received: ago(40),
      intake: "Jordan Hale",
      manager: "Dana Lewis",
      source: "Howard County AERS",
      sourceContact: "",
      submittedTo: "Cottage MD",
      status: "Declined — family chose other",
      reason: "Chose competitor",
      ids: ["CHC10220"],
      lastNoteAt: ago(28),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(30, "Jordan Hale", "Conversation", "Spoke with son — they selected another agency."),
        note(28, "Jordan Hale", "Note", "Closed. Wish them well."),
      ],
    },
    {
      id: "KOWALSKI||22108",
      srno: "22108",
      name: "Kowalski, Anna",
      branch: "Queens",
      state: "NY",
      received: ago(15),
      intake: "Priya Shah",
      manager: "Elena Ruiz",
      source: "NYC HRA",
      sourceContact: "Unit 4",
      submittedTo: "Cottage NY",
      status: "Initial Screening",
      reason: "",
      ids: ["CHC22108"],
      lastNoteAt: ago(12),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(15, "Priya Shah", "Intake", "New pt Queens. CHC-22108."),
        note(12, "Priya Shah", "Outreach", "Left a VM. No response."),
      ],
    },
    {
      id: "ORTEGA||22091",
      srno: "22091",
      name: "Ortega, Luis",
      branch: "Bronx",
      state: "NY",
      received: ago(8),
      intake: "Priya Shah",
      manager: "Elena Ruiz",
      source: "Montefiore CM",
      sourceContact: "I. Diaz",
      submittedTo: "Cottage NY",
      status: "Open",
      reason: "",
      ids: ["CHC22091"],
      lastNoteAt: ago(4),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(8, "Priya Shah", "Intake", "D/C this week. 6 hours PCA."),
        note(4, "Priya Shah", "Conversation", "Spoke with member. Informed that aide start is pending matching."),
      ],
    },
    {
      id: "HASSAN||21944",
      srno: "21944",
      name: "Hassan, Fatima",
      branch: "Brooklyn",
      state: "NY",
      received: ago(24),
      intake: "Chris Bell",
      manager: "Elena Ruiz",
      source: "Maimonides",
      sourceContact: "SW Desk",
      submittedTo: "Cottage NY",
      status: "Open",
      reason: "",
      ids: ["CHC21944"],
      lastNoteAt: ago(18),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(24, "Chris Bell", "Intake", "New patient. Language: Arabic. Daughter translates."),
        note(21, "Chris Bell", "Outreach", "No answer, left a VM."),
        note(18, "Chris Bell", "Outreach", "Left a text. Not going thru on the landline."),
      ],
    },
    {
      id: "PARK||22140",
      srno: "22140",
      name: "Park, Helen",
      branch: "Nassau",
      state: "NY",
      received: ago(6),
      intake: "Chris Bell",
      manager: "Elena Ruiz",
      source: "Northwell",
      sourceContact: "CM Park",
      submittedTo: "Cottage NY",
      status: "Scheduling",
      reason: "",
      ids: ["CHC22140"],
      lastNoteAt: ago(2),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(6, "Chris Bell", "Intake", "Screening is on the calendar."),
        note(2, "Chris Bell", "Scheduling", "Level 1 set for Friday 10:30. Send reminder Thursday."),
      ],
    },
    {
      id: "KLEIN||21802",
      srno: "21802",
      name: "Klein, Robert",
      branch: "Manhattan",
      state: "NY",
      received: ago(45),
      intake: "Priya Shah",
      manager: "Elena Ruiz",
      source: "Mt Sinai",
      sourceContact: "",
      submittedTo: "Cottage NY",
      status: "Admitted — started",
      reason: "",
      ids: ["CHC21802"],
      lastNoteAt: ago(20),
      sourceFile: "seed",
      updatedAt: Date.now(),
      notes: [
        note(22, "Priya Shah", "Conversation", "Spoke with member. Aide started Monday."),
        note(20, "Priya Shah", "Note", "Moved to started. Handed to ops."),
      ],
    },
  ];
  return Object.fromEntries(rows.map((c) => [c.id, c]));
}

export function seedTasks(): Record<string, PipelineTask> {
  const rows: PipelineTask[] = [
    {
      id: "act-recert",
      title: "Recert packet — Walsh family",
      assignee: "Maya Ortiz",
      patient: "Walsh, Eleanor",
      state: "MD",
      priority: "high",
      due: ago(0, 11),
      status: "Open",
      source: "Pipeline",
      ref: "CHC10412",
      notes: [
        {
          id: uid(),
          text: "Packet sitting on the desk since yesterday. Needs a signature chase.",
          at: ago(1),
          byName: "Maya Ortiz",
        },
      ],
      createdAt: ago(2),
      createdByName: "Maya Ortiz",
      updatedAt: Date.now(),
    },
    {
      id: "act-aers",
      title: "AERS callback — PG County",
      assignee: "Maya Ortiz",
      patient: "Chen, Marcus",
      state: "MD",
      priority: "critical",
      due: ago(0, 9),
      status: "Open",
      source: "Pipeline",
      ref: "CHC10388",
      notes: [],
      createdAt: ago(1),
      createdByName: "Maya Ortiz",
      updatedAt: Date.now(),
    },
    {
      id: "act-staff",
      title: "Staffing hold — Silver Spring zip",
      assignee: "Jordan Hale",
      patient: "Patel, Priya",
      state: "MD",
      priority: "medium",
      due: ago(-1, 16),
      status: "Waiting on agency",
      source: "Pipeline",
      ref: "CHC10440",
      notes: [],
      createdAt: ago(3),
      createdByName: "Jordan Hale",
      updatedAt: Date.now(),
    },
    {
      id: "act-docs",
      title: "Confirm documents posted — Brooks",
      assignee: "Maya Ortiz",
      patient: "Brooks, DeShawn",
      state: "MD",
      priority: "medium",
      due: ago(-2, 12),
      status: "Open",
      source: "Pipeline",
      ref: "CHC10391",
      notes: [],
      createdAt: ago(4),
      createdByName: "Maya Ortiz",
      updatedAt: Date.now(),
    },
  ];
  return Object.fromEntries(rows.map((t) => [t.id, t]));
}

export function seedReminders(operator: string): Record<string, Reminder> {
  const huddle = new Date();
  huddle.setHours(8, 30, 0, 0);
  if (huddle.getTime() < Date.now()) huddle.setDate(huddle.getDate() + 1);
  const call = new Date(Date.now() + 45 * 60 * 1000);
  return {
    "rem-huddle": {
      id: "rem-huddle",
      title: "Morning huddle",
      body: "Screening, stale, due — one pass before the phones get loud.",
      at: huddle.getTime(),
      repeat: "daily",
      itemKey: "",
      status: "open",
      createdAt: Date.now(),
      createdBy: operator || "JARVIS",
    },
    "rem-walsh": {
      id: "rem-walsh",
      title: "Call Eleanor Walsh",
      body: "Two missed outreach attempts. Try the daughter's number.",
      at: call.getTime(),
      repeat: "once",
      itemKey: "case:WALSH||10412",
      status: "open",
      createdAt: Date.now(),
      createdBy: operator || "JARVIS",
    },
  };
}

export function seedNetwork(): NetworkRecord[] {
  return [
    {
      _id: "md",
      name: "Maryland (MD)",
      region: "Mid-Atlantic",
      Agency_NAME: "Cottage Homecare of Maryland",
      address: "7200 Wisconsin Ave, Bethesda, MD",
      NPI: "1487654321",
      Tax_ID: "52-1234567",
      medicaid_id: "MD-CHC-0192",
      provider_id: "MD192",
      vendor_id: "V-10412",
      lara_id: "—",
      phone: "(410) 555-0142",
      fax: "(410) 555-0143",
      email: "intake.md@cottagehomecare.com",
      pay_rate: "State fee schedule",
      img: "",
      local: true,
    },
    {
      _id: "ny",
      name: "New York (NY)",
      region: "Northeast",
      Agency_NAME: "Cottage Homecare of New York",
      address: "2 Park Ave, New York, NY",
      NPI: "1678901234",
      Tax_ID: "13-9876543",
      medicaid_id: "NY-CHC-2201",
      provider_id: "NY2201",
      vendor_id: "V-22091",
      lara_id: "—",
      phone: "(718) 555-0190",
      fax: "(718) 555-0191",
      email: "intake.ny@cottagehomecare.com",
      pay_rate: "MLTC / CHHA mix",
      img: "",
      local: true,
    },
    {
      _id: "nj",
      name: "New Jersey (NJ)",
      region: "Northeast",
      Agency_NAME: "Cottage Homecare of New Jersey",
      address: "101 Hudson St, Jersey City, NJ",
      NPI: "1567890123",
      Tax_ID: "22-4455667",
      medicaid_id: "NJ-CHC-0881",
      provider_id: "NJ881",
      vendor_id: "V-0881",
      lara_id: "—",
      phone: "(201) 555-0177",
      fax: "(201) 555-0178",
      email: "intake.nj@cottagehomecare.com",
      pay_rate: "Medicaid PCA",
      img: "",
      local: true,
    },
    {
      _id: "pa",
      name: "Pennsylvania (PA)",
      region: "Mid-Atlantic",
      Agency_NAME: "Cottage Homecare of Pennsylvania",
      address: "1700 Market St, Philadelphia, PA",
      NPI: "1456789012",
      Tax_ID: "23-3344556",
      medicaid_id: "PA-CHC-4410",
      provider_id: "PA4410",
      vendor_id: "V-4410",
      lara_id: "—",
      phone: "(215) 555-0110",
      fax: "(215) 555-0111",
      email: "intake.pa@cottagehomecare.com",
      pay_rate: "OLTL",
      img: "",
      local: true,
    },
    {
      _id: "fl",
      name: "Florida (FL)",
      region: "Southeast",
      Agency_NAME: "Cottage Homecare of Florida",
      address: "201 S Biscayne Blvd, Miami, FL",
      NPI: "1345678901",
      Tax_ID: "59-7788990",
      medicaid_id: "FL-CHC-3302",
      provider_id: "FL3302",
      vendor_id: "V-3302",
      lara_id: "—",
      phone: "(305) 555-0160",
      fax: "(305) 555-0161",
      email: "intake.fl@cottagehomecare.com",
      pay_rate: "Long-term care waiver",
      img: "",
      local: true,
    },
    {
      _id: "mi",
      name: "Michigan (MI)",
      region: "Midwest",
      Agency_NAME: "Riverside Select DBA Cottage Homecare",
      address: "150 W Jefferson, Detroit, MI",
      NPI: "1234567890",
      Tax_ID: "38-1122334",
      medicaid_id: "MI-CHC-0911",
      provider_id: "MI911",
      vendor_id: "V-0911",
      lara_id: "LARA-44019",
      phone: "(313) 555-0128",
      fax: "(313) 555-0129",
      email: "intake.mi@cottagehomecare.com",
      pay_rate: "MI Choice",
      img: "",
      local: true,
    },
  ];
}
